UNIVERSES = [
    {
        "id": 1,
        "title": "Universo 1: Polleria Espacial",
        "short": "Polleria Espacial",
        "mechanic": "galaga",
        "background": "Backgrounds/universo_1_espacio.png",
        "player_state": "angry",
        "goal": "Derrota al Cometa Brasa disparando aji laser.",
        "target": 12,
        "boss_trigger": 12,
        "enemy_rate": 1.05,
        "enemies": [
            ("brasa_espacial", "Enemies/space/brasa_espacial.png", 1, 15),
            ("papa_alienigena", "Enemies/space/papa_alienigena.png", 1, 12),
            ("gaseosa_flotante", "Enemies/space/gaseosa_flotante.png", 1, 10),
        ],
        "boss": ("El Cometa Brasa", "Bosses/cometa_brasa.png", 18, 350),
        "lose_phrase": "Te dio una indigestion por tragar mucho pollito .......",
        "clear_phrase": "Portal abierto: la brasa espacial fue derrotada.",
    },
    {
        "id": 2,
        "title": "Universo 2: Universidad del Pollo",
        "short": "Universidad del Pollo",
        "mechanic": "collect",
        "background": "Backgrounds/universo_2_universidad.png",
        "player_state": "shock",
        "goal": "Recoge libros y sobrevive al Examen Final de Grafica.",
        "target": 8,
        "boss_trigger": 8,
        "enemy_rate": 0.95,
        "enemies": [
            ("Parcial de Grafica", "Enemies/university/parcial_grafica.png", 1, 15),
            ("Tarea acumulada", "Enemies/university/tarea_acumulada.png", 1, 12),
            ("Mi Grupo me abandono", "Enemies/university/grupo_abandono.png", 1, 18),
        ],
        "collectible": ("Libro de Grafica", "Powerups/libro.png", 1, 1),
        "boss": ("El Examen Final de Grafica 3 horas", "Bosses/examen_final_grafica.png", 20, 400),
        "lose_phrase": "Ya fui, me voy al susti en Grafica........",
        "clear_phrase": "Aprobaste Grafica y no se como!!!!",
    },
    {
        "id": 3,
        "title": "Universo 3: Delivery Infernal",
        "short": "Delivery Infernal",
        "mechanic": "runner",
        "background": "Backgrounds/universo_3_delivery.png",
        "player_state": "excited",
        "goal": "Corre, salta y derrota al Motorizado Supremo.",
        "target": 520,
        "boss_trigger": 520,
        "enemy_rate": 1.05,
        "enemies": [
            ("Moto", "Enemies/delivery/moto.png", 1, 14),
            ("Hueco", "Enemies/delivery/hueco.png", 1, 10),
            ("Ticket de pedido", "Enemies/delivery/ticket_delivery.png", 1, 12),
            ("Cliente hambriento", "Enemies/delivery/cliente_hambriento.png", 1, 16),
        ],
        "powerups": [
            ("Aji turbo", "Powerups/aji_turbo.png", "turbo"),
            ("Mayonesa shield", "Powerups/mayonesa_shield.png", "shield"),
            ("Gaseosa speed", "Powerups/gaseosa_speed.png", "turbo"),
        ],
        "boss": ("El Motorizado Supremo", "Bosses/motorizado_supremo.png", 12, 420),
        "lose_phrase": "El chamo te quito la chamba.........",
        "clear_phrase": "Escapaste a la moto extorsionadora del chamo.",
    },
    {
        "id": 4,
        "title": "Universo 4: La Oficina del Pollo Adulto",
        "short": "Oficina del Pollo Adulto",
        "mechanic": "office",
        "background": "Backgrounds/universo_4_oficina.png",
        "player_state": "cry",
        "goal": "Recolecta cafe, dinero y descanso. Sobrevive al fin de mes.",
        "target": 9,
        "boss_trigger": 9,
        "enemy_rate": 0.75,
        "enemies": [
            ("Recibo de luz", "Enemies/office/recibo_luz.png", 1, 13),
            ("Correo urgente", "Enemies/office/correo_urgente.png", 1, 12),
            ("Reunion sorpresa", "Enemies/office/reunion_sorpresa.png", 1, 15),
            ("Deuda con cara malvada", "Enemies/office/deuda_malvada.png", 1, 18),
            ("Trafico", "Enemies/office/trafico.png", 1, 14),
        ],
        "powerups": [
            ("Cafe", "Powerups/cafe.png", "score"),
            ("Dinero", "Powerups/dinero.png", "score"),
            ("Descanso", "Powerups/descanso.png", "heal"),
        ],
        "boss": ("El Pago de Fin de Mes", "Bosses/pago_fin_de_mes.png", 22, 420),
        "lose_phrase": "¿Que hago con mi vida?",
        "clear_phrase": "Sobreviviste al cierre de mes. Nadie sabe como.",
    },
]

FINAL_PHRASE = "La vida da vueltas, como un pollo a la brasa .......... te toca sobrevivir a todo."
